repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: rabbitmq
    namespace: rabbitmq
    chart: bitnami/rabbitmq
    version: 16.0.9
    values:
      - auth:
          username: admin
          password: StrongRabbitPass123!
        metrics:
          enabled: true
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: rabbitmq.local
          servicePort: 15672
          selfSigned: true
